### ISSUE TITLE
Ideia

### ISSUE THREAD

**Issue by ygorlazaro** [qmpedro/MeuTioOperouREST#1]
Qual a ideia desse projeto? Ex-desenv pode participar?

**Comment by qmpedro** [comment]
É meu app de rest. Pra testar post e gerar base64 de imagem principalmente
hehehe
Quer fazer melhoria?

Em sábado, 21 de novembro de 2015, Ygor Lazaro notifications@github.com
escreveu:

> Qual a ideia desse projeto? Ex-desenv pode participar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qmpedro/MeuTioOperouREST/issues/1.

## 

Enviado do iPad

**Comment by ygorlazaro** [comment]
Vou fazer um fork e dar uma olhada, mas acho que sim :)
